avalon/avalon/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^', include('avalon_game.urls')),
]

avalon/avalon_game/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^join/$', views.enter_code, name='enter_code'),
    url(r'^new/$', views.new_game, name='new_game'),
    url(r'^(?P<access_code>[a-zA-Z]{6})/', include([
        url(r'^$', views.join_game, name='join_game'),
        url(r'^qr/$', views.qr_code, name='qr_code'),
        url(r'^results/$', views.game_results, name='game_results'),
        url(r'^observe/', include([
            url(r'^$', views.observe, name='observe'),
            url(r'^status/$', views.observe_status, name='observe_status'),
            url(r'^start/$', views.observe_start, name='observe_start'),
            url(r'^cancel_game/$', views.observe_cancel_game, name='observe_cancel_game'),
            url(r'^next_game/$', views.observe_next_game, name='observe_next_game'),
        ])),
        url(r'(?P<player_secret>[a-z]{8})/', include([
            url(r'^$', views.game, name='game'),
            url(r'^status/$', views.status, name='status'),
            url(r'^start/$', views.start, name='start'),
            url(r'^leave/$', views.leave, name='leave'),
            url(r'^ready/$', views.ready, name='ready'),
            url(r'^next_game/$', views.next_game, name='next_game'),
            url(r'^cancel_game/$', views.cancel_game, name='cancel_game'),
            url(r'^(?P<round_num>[1-5])/(?P<vote_num>[1-5])/', include([
                url(r'^vote/(?P<vote>(approve|reject|cancel))/$', views.vote, name='vote'),
                url(r'^choose/(?P<who>[0-9])/$', views.choose, name='choose'),
                url(r'^unchoose/(?P<who>[0-9])/$', views.unchoose, name='unchoose'),
                url(r'^finalize_team/$', views.finalize_team, name='finalize_team'),
                url(r'^retract_team/$', views.retract_team, name='retract_team'),
            ])),
            url(r'^mission/(?P<round_num>[1-5])/(?P<mission_action>(success|fail))/$', views.mission, name='mission'),
            url(r'^assassinate/(?P<target>[0-9])/$', views.assassinate, name='assassinate'),
        ])),
    ])),
]

avalon/avalon_game/models.py
from __future__ import unicode_literals

from datetime import datetime, timedelta
import random
import string

from django.db import models, transaction
from django.utils import timezone

from .helpers import mission_size, mission_size_string

def generate_code(length):
    return "".join([random.choice(string.ascii_lowercase)
                    for i in range(length)])

class Game(models.Model):
    ACCESS_CODE_LENGTH = 6
    access_code = models.CharField(db_index=True, unique=True,
                                   max_length=ACCESS_CODE_LENGTH)
    GAME_PHASE_LOBBY = 0
    GAME_PHASE_ROLE = 1
    GAME_PHASE_PICK = 2
    GAME_PHASE_VOTE = 3
    GAME_PHASE_MISSION = 4
    GAME_PHASE_ASSASSIN = 5
    GAME_PHASE_END = 6
    game_phase = models.IntegerField(default=GAME_PHASE_LOBBY)
    times_started = models.IntegerField(null=False, default=0)
    display_history = models.NullBooleanField()
    private_voting = models.NullBooleanField()
    player_assassinated = models.ForeignKey('Player', null=True, default=None,
                                            related_name='+',
                                            on_delete=models.PROTECT)
    created = models.DateTimeField()
    ended = models.DateTimeField(null=True, default=None)
    next_game = models.OneToOneField('self', null=True, default=None,
                                     related_name='previous_game',
                                     on_delete=models.SET_DEFAULT)

    # from http://stackoverflow.com/a/11821832
    def save(self, *args, **kwargs):
        # object is being created, thus no primary key field yet
        if not self.pk:
            # Make sure access_code is unique before using it.
            access_code = generate_code(Game.ACCESS_CODE_LENGTH)
            while Game.objects.filter(access_code=access_code).exists():
                access_code = generate_code(Game.ACCESS_CODE_LENGTH)
            self.access_code = access_code
            self.created = timezone.now()
        if self.ended is None and self.game_phase == Game.GAME_PHASE_END:
            self.ended = timezone.now()
        super(Game, self).save(*args, **kwargs)

    _game_phase_strings = {
        GAME_PHASE_LOBBY: 'lobby',
        GAME_PHASE_ROLE: 'role',
        GAME_PHASE_PICK: 'pick',
        GAME_PHASE_VOTE: 'vote',
        GAME_PHASE_MISSION: 'mission',
        GAME_PHASE_ASSASSIN: 'assassin',
        GAME_PHASE_END: 'end',
    }
    def game_phase_string(self):
        return Game._game_phase_strings[self.game_phase]

    def num_players(self):
        return self.player_set.count()

    # The global settings make everything atomic... this is just to annotate
    #   that it's important that we never create two next games.
    @transaction.atomic
    def create_or_get_next_game(self):
        if self.next_game is None and self.game_phase == self.GAME_PHASE_END:
            self.next_game = Game.objects.create()
            self.save()
        return self.next_game

class Player(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE, db_index=True)
    SECRET_ID_LENGTH = 8
    secret_id = models.CharField(db_index=True, max_length=SECRET_ID_LENGTH)
    name = models.CharField(max_length=80)
    ROLE_SPY = -1
    ROLE_ASSASSIN = -2
    ROLE_MORGANA = -3
    ROLE_MORDRED = -4
    ROLE_OBERON = -5
    ROLE_GOOD = 1
    ROLE_MERLIN = 2
    ROLE_PERCIVAL = 3
    role = models.IntegerField(null=True, default=None)
    order = models.IntegerField(null=True, default=None)
    ready = models.BooleanField(default=False)
    joined = models.DateTimeField()
    last_accessed = models.DateTimeField()
    # names are unique in a game
    unique_together = (("game", "name"), ("game", "secret_id"))

    def is_expired(self):
        return timezone.now() - self.last_accessed > timedelta(seconds=10)

    def change_secret_id(self):
        # Make sure secret_id is unique before using it.
        secret_id = generate_code(Player.SECRET_ID_LENGTH)
        while Player.objects.filter(game=self.game,
                                    secret_id=secret_id).exists():
            secret_id = generate_code(Player.SECRET_ID_LENGTH)
        self.secret_id = secret_id

    # from http://stackoverflow.com/a/11821832
    def save(self, *args, **kwargs):
        # object is being created, thus no primary key field yet
        if not self.pk:
            self.change_secret_id()
            self.joined = timezone.now()
        self.last_accessed = timezone.now()
        super(Player, self).save(*args, **kwargs)

    def is_spy(self):
        if self.role is None:
            return None
        elif self.role < 0:
            return True
        else:
            return False

    def team(self):
        if self.is_spy() is None:
            return None
        elif self.is_spy():
            return 'spy'
        else:
            return 'resistance'

    def role_string(self):
        if self.role is None:
            return None
        elif self.role == Player.ROLE_SPY:
            return "Minion of Mordred"
        elif self.role == Player.ROLE_ASSASSIN:
            return "Assassin"
        elif self.role == Player.ROLE_MORGANA:
            return "Morgana"
        elif self.role == Player.ROLE_MORDRED:
            return "Mordred"
        elif self.role == Player.ROLE_OBERON:
            return "Oberon"
        elif self.role == Player.ROLE_GOOD:
            return "Loyal servant of Arthur"
        elif self.role == Player.ROLE_MERLIN:
            return "Merlin"
        elif self.role == Player.ROLE_PERCIVAL:
            return "Percival"

    def is_oberon(self):
        return self.role == Player.ROLE_OBERON

    def is_merlin(self):
        return self.role == Player.ROLE_MERLIN

    def is_percival(self):
        return self.role == Player.ROLE_PERCIVAL

    def is_assassin(self):
        return self.role == Player.ROLE_ASSASSIN

    def is_morgana(self):
        return self.role == Player.ROLE_MORGANA

    def is_mordred(self):
        return self.role == Player.ROLE_MORDRED

    def sees_as_spy(self, other):
        if other.is_spy():
            if self.is_merlin() and not other.is_mordred():
                return True
            elif self.is_spy() and\
                    not self.is_oberon() and not other.is_oberon():
                return True
        return False

    def appears_as_merlin(self):
        return self.is_merlin() or self.is_morgana()

class GameRoundManager(models.Manager):
    def get_current_game_round(self, game):
        return self.filter(game=game).order_by('-round_num').first()

class GameRound(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE, db_index=True)
    round_num = models.IntegerField()
    unique_together = (("game", "round_num"),)
    mission_passed = models.NullBooleanField()

    objects = GameRoundManager()

    def winner_string(self):
        if self.mission_passed is None:
            return ''
        elif self.mission_passed:
            return 'resistance'
        else:
            return 'spy'

    def result_string(self):
        if self.mission_passed is None:
            return ''
        elif self.mission_passed:
            return 'pass'
        else:
            return 'fail'

    def mission_size_tuple(self):
        num_players = Player.objects.filter(game=self.game).count()
        return mission_size(num_players=num_players,
                            round_num=self.round_num)

    def mission_size_string(self):
        return mission_size_string(self.mission_size_tuple())

    def num_players_on_mission(self):
        return self.mission_size_tuple()[0]

    def num_fails_required(self):
        return self.mission_size_tuple()[1]

    def num_fails(self):
        if self.mission_passed is None:
            return None
        else:
            return self.missionaction_set.filter(played_success=False).count()

    def played_fail(self):
        if self.mission_passed is None:
            return None
        else:
            fail_actions = self.missionaction_set.filter(played_success=False)
            return [action.player for action in fail_actions]

class MissionAction(models.Model):
    game_round = models.ForeignKey(GameRound, on_delete=models.CASCADE, db_index=True)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    unique_together = (("game", "player"),)
    played_success = models.BooleanField()

class VoteRoundManager(models.Manager):
    def get_current_vote_round(self, game=None, game_round=None):
        if game_round is None:
            game_round = GameRound.objects.get_current_game_round(game=game)
        return self.filter(game_round=game_round).order_by('-vote_num').first()

class VoteRound(models.Model):
    game_round = models.ForeignKey(GameRound, on_delete=models.CASCADE, db_index=True)
    vote_num = models.IntegerField()
    unique_together = (("game_round", "vote_num"),)
    VOTE_STATUS_WAITING = 0
    VOTE_STATUS_VOTING = 1
    VOTE_STATUS_VOTED = 2
    vote_status = models.IntegerField(default=VOTE_STATUS_WAITING)
    leader = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='vote_round_leader')
    chosen = models.ManyToManyField(Player, related_name='vote_round_chosen')
    started = models.DateTimeField()
    chose_team = models.DateTimeField(null=True, default=None)
    voted = models.DateTimeField(null=True, default=None)

    objects = VoteRoundManager()

    def is_team_finalized(self):
        return self.vote_status != VoteRound.VOTE_STATUS_WAITING

    def is_waiting_on_leader(self):
        return self.vote_status == VoteRound.VOTE_STATUS_WAITING

    def is_currently_voting(self):
        return self.vote_status == VoteRound.VOTE_STATUS_VOTING

    def is_voting_complete(self):
        return self.vote_status == VoteRound.VOTE_STATUS_VOTED

    def is_first_vote(self):
        return self.vote_num == 1

    def is_chosen_correct_size(self):

avalon/avalon_game/forms.py
from django import forms

from .models import Game, Player

class NewGameForm(forms.Form):
    name = forms.CharField(label='Name', max_length=80, required=False)

    def clean(self):
        cleaned_data = super(NewGameForm, self).clean()

        name = cleaned_data.get("name")
        observer = 'observe' in self.data

        if observer and (name is None or len(name) > 0):
            self.add_error('name', "Only fill in 'Name' field if you will be playing (not observing) using this device.")
        elif not observer and len(name) == 0:
            self.add_error('name', "Player name must be non-empty (did you mean to click 'Create as observer'?).")

        if name is None or observer:
            cleaned_data["name"] = None

class JoinGameForm(forms.Form):
    game = forms.CharField(label='Access code',
                           max_length=Game.ACCESS_CODE_LENGTH)
    player = forms.CharField(label='Name', max_length=80, required=False)

    def clean_game(self):
        data = self.cleaned_data['game']

        try:
            return Game.objects.get(access_code=data.lower())
        except Game.DoesNotExist:
            raise forms.ValidationError("Invalid access code.")

    def clean(self):
        cleaned_data = super(JoinGameForm, self).clean()

        game = cleaned_data.get("game")
        name = cleaned_data.get("player")
        observer = 'observe' in self.data
        cleaned_data["observer"] = observer

        if game.game_phase == Game.GAME_PHASE_END:
            cleaned_data["player"] = None
            return

        if observer and (name is None or len(name) > 0):
            self.add_error('player', "Leave 'Name' field blank if observing or use 'Join' button to join as a player.")
        elif not observer and len(name) == 0:
            self.add_error('player', "Player name must be non-empty (did you mean to click 'Observe'?).")
            return

        if game is None or name is None or observer:
            cleaned_data["player"] = None
            return

        previous_game = None
        try:
            previous_game = game.previous_game
        except Game.DoesNotExist:
            pass
        if previous_game is not None:
            try:
                player = Player.objects.get(game=previous_game, name=name)
                if not player.is_expired():
                    self.add_error('player', "Please choose a different name; there is already a player using that name.")
                    self.add_error('player', "Please try again in a few seconds if you are trying to rejoin.")
            except Player.DoesNotExist:
                pass

        try:
            player = Player.objects.get(game=game, name=name)
            if player.is_expired():
                player.change_secret_id();
                player.save()
                cleaned_data["player"] = player
            else:
                self.add_error('player', "Please choose a different name; there is already a player using that name.")
                self.add_error('player', "Please try again in a few seconds if you are trying to rejoin.")
        except Player.DoesNotExist:
            if game.game_phase == Game.GAME_PHASE_LOBBY:
                player = Player.objects.create(game=game, name=name)
                cleaned_data["player"] = player
            else:
                self.add_error('player', "That game has already started. If you want to rejoin, please enter your name exactly as you did before or select \"Observe\" if you just want to display the game status.")

class StartGameForm(forms.Form):
    display_history = forms.BooleanField(required=False, initial=True,
                                         label="show history table")
    private_voting = forms.BooleanField(required=False, initial=True,
                                         label="private voting (only reveal vote totals)")
    merlin = forms.BooleanField(required=False, initial=True, label="Merlin")
    percival = forms.BooleanField(required=False, initial=True,
                                  label="Percival")
    assassin = forms.BooleanField(required=False, initial=True,
                                  label="Assassin")
    morgana = forms.BooleanField(required=False, initial=True, label="Morgana")
    mordred = forms.BooleanField(required=False, initial=False,
                                 label="Mordred")
    oberon = forms.BooleanField(required=False, initial=False, label="Oberon")

    def clean(self):
        cleaned_data = super(StartGameForm, self).clean()

        merlin = cleaned_data.get("merlin")
        percival = cleaned_data.get("percival")
        assassin = cleaned_data.get("assassin")
        morgana = cleaned_data.get("morgana")
        mordred = cleaned_data.get("mordred")

        if assassin and not merlin:
            self.add_error('assassin', "The assassin requires Merlin to be in the game.")
        if percival and not merlin:
            self.add_error('percival', "Percival requires Merlin to be in the game.")
        if morgana and (not merlin or not percival):
            self.add_error('morgana', "Morgana requies Merlin and Percival to be in the game.")
        if mordred and not merlin:
            self.add_error('mordred', "Mordred requires Merlin to be in the game.")

avalon/avalon_game/templates/assassinate.html
{% extends "in_game.html" %}

{% block game_content %}
  <div class="assassin-phase">
    <h2>Assassin Phase</h2>

    <p>
      Correctly guess the identity of Merlin to win the game:
    </p>
    <ul>
      {% for p in targets %}
      <li class="player">
        <form method="post" action="{% url 'assassinate' access_code=access_code player_secret=player_secret target=p.order %}">
          {% csrf_token %}
          <div class="button-container">
            <button type="submit">{{ p.name }}</button>
          </div>
        </form>
      </li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

avalon/avalon_game/templates/assassinate_wait.html
{% extends "in_game.html" %}

{% block game_content %}
  <div class="assassin-phase">
    <p>
      The resistance have won 3 rounds! Please wait while the assassin choses a target.
    </p>
  </div>
{% endblock %}

avalon/avalon_game/templates/base.html
{% load static %}
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/skeleton.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" type="text/css">
  <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
  <title>Resistance</title>
</head>

<body>
  <div class="container">
    {% block accesscode %}
    <div class="access-code">
      <p>
        <span class="header">Access Code</span> {% block accesscode_value %}{{ access_code|default:"(not in game)" }}{% endblock %}
        {% if not results_only %}<span class="header">Name</span> {% if is_observer %}(observer){% else %}{{ player.name|default:"(not in game)" }}{% endif %}{% endif %}
      </p>
    </div>
    {% endblock %}
    {% block score %}
    <div class="score">
      {% for round_num, round in round_scores.items %}
      <div class="score-box {{ round.result }}"><p id="score-box-{{ round_num }}">{{ round.mission_size }}</p></div>
      {% empty %}
      <div class="score-box"><p id="score-box-1"></p></div>
      <div class="score-box"><p id="score-box-2"></p></div>
      <div class="score-box"><p id="score-box-3"></p></div>
      <div class="score-box"><p id="score-box-4"></p></div>
      <div class="score-box"><p id="score-box-5"></p></div>
      {% endfor %}
    </div>
    {% endblock %}
    <br>
    {% block content %}{% endblock %}
    <br>
    {% block history %}{% endblock %}
    <hr>

    <p class="small"><a href="https://boardgamegeek.com/boardgame/41114/resistance" target="_blank">The Resistance: Avalon</a> was designed by Don Eskridge </p>
    <p class="small">and published by <a href="http://www.indieboardsandcards.com/resistance.php">Indie Cards and Games</a></p>
    <p class="small">Built by <a href="https://aweirdimagination.net/" target="_blank">Daniel Perelman</a> based on <a href="http://alantran.co" target="_blank">Alan Tran</a>'s <a href="https://github.com/athtran/avalon" target="_blank">Avalon app</a> | <a href="https://github.com/dperelman/avalon-django" target="_blank">Github Link</a></p>
  </div>
</body>

avalon/avalon_game/templates/end.html
{% extends "in_game.html" %}

{% block accesscode_value %}<a href = "{% url 'game_results' access_code=access_code %}">{{ access_code }} (results permalink)</a>{% endblock %}
{% block game_content %}
<div class="gameOver">
  <h2>{% if resistance_won %}Resistance{% else %}Spies{% endif %} Won!</h2>

  {% if player_assassinated %}
  <p>
  The assassin targetted {{ player_assassinated.name }} who was{% if not player_assassinated.is_merlin %} not{% endif %} Merlin.
  </p>
  {% endif %}

  <p>
    Player roles:
    <table id="role-reveal">
      <tr>
        <th>Name</th>
        <th>Role</th>
      </tr>
      {% for p in players %}
      <tr>
        <td><span class="{{ p.team }}">{{ p.name }}</span></td>
        <td><span class="{{ p.team }}">{{ p.role_string }}</span></td>
      </tr>
      {% endfor %}
    </table>
  </p>
</div>

{% if results_only %}
    {% if previous_game %}
        <div class="button-container">
            <a href="{% url 'game_results' access_code=previous_game.access_code  %}" class="button" id="button-prev-game-results">View previous game</a>
        </div>
    {% endif %}
    {% if next_game %}
        {% if next_game_ongoing %}
        <div class="button-container">
            <a href="{% url 'observe' access_code=next_game.access_code  %}" class="button" id="button-observe-next-game">Observe next game</a>
        </div>
        {% else %}
        <div class="button-container">
            <a href="{% url 'game_results' access_code=next_game.access_code  %}" class="button" id="button-next-game-results">View next game</a>
        </div>
        {% endif %}
    {% endif %}
{% else %}
<div class="button-container">
    <a href="{% if is_observer %}{% url 'observe_next_game' access_code=access_code %}{% else %}{% url 'next_game' access_code=access_code player_secret=player.secret_id %}{% endif %}" class="button" id="button-{% if next_game %}join{% else %}start{% endif %}-next-game">{% if next_game %}Join{% else %}Start{% endif %} new game</a>
</div>
{% endif %}
<div class="button-container">
    <a href="{% url 'index' %}" class="button" id="button-home">Exit game</a>
</div>
{% endblock %}

avalon/avalon_game/templates/in_game.html
{% extends "game.html" %}

{% block game_header %}
  <div class="available-roles">
    There are <b>{{ num_players }}</b> players:
    <b class="spy">{{ num_spies }} spies</b>
    {% if spy_roles %}
      (including special roles
      {% for role in spy_roles %}
        {% if forloop.last and not forloop.first %}and{% endif %}
        <b class = "spy">{{ role }}</b>
      {% endfor %})
    {% endif %}
    and
    <b class = "resistance">{{ num_resistance }} resistance</b>
    {% if resistance_roles %}
      (including special roles
      {% for role in resistance_roles %}
        {% if forloop.last and not forloop.first %}and{% endif %}
        <b class = "resistance">{{ role }}</b>
      {% endfor %})
    {% endif %}
  </div>
  <div class="role-info">
    <hr class="small-hr">
    {% if not is_observer %}
    <div id="role-info">
      <p>Team: <b class="{{ player.team }}">{{ player.team|title }}</b> | Role: {{ player.role_string }}</p>

      {% if player.is_spy and not player.is_oberon %}
      <p>Other spies:
        {% for spy in visible_spies %}
        {% if spy != player %}
        <b class="spy">{{ spy.name }} </b>
        {% endif %}
        {% endfor %}
      </p>
      {% endif %}

      {% if player.is_merlin %}
      <p>The spies {% if game_has_mordred %}(except Mordred){% endif %} are:
        {% for spy in visible_spies %}
        <b class="spy">{{ spy.name }} </b>
        {% endfor %}
      </p>
      {% endif %}

      {% if player.is_percival %}
      <p>Merlin is {{ possible_merlins }}.</p>
      {% endif %}

      {% if player.is_assassin %}
      <p>Try to see if you can spot who the Merlin is. You'll have a chance to identify him at the end of the game to win it.</p>
      {% endif %}

      {% if player.is_morgana %}
      <p>Percival sees you as Merlin.</p>
      {% endif %}

      {% if player.is_mordred %}
      <p>Merlin does not know you are a spy.</p>
      {% endif %}
    </div>
    <p id="role-info-hidden">
      Tap to view role info
    </p>
  </div>
  {% endif %}

  <script>
    $(document).ready(function () {
      $('.role-info').click(function () {
        $('#role-info').toggle();
        $('#role-info-hidden').toggle();
      })
    })
  </script>
{% endblock %}

{% block history %}
{{ debug }}
{% if not display_history and not game_over %}
<table id="player_order">
    <thead>
        <tr>
            <th>Leader order</th>
        </tr>
    </thead>
    <tbody>
        {% for p in players %}
        <tr>
            <td>{{ p.name }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<table id="history">
  <thead>
    <tr>
      <th class="accept"></th>
      <th class="reject"></th>
      {% for p in players %}
      <th><p><span{% if game_over %} class="{{ p.team }}"{% endif %}>{{ p.name }}</span></p></th>
      {% endfor %}
    </tr>
    {% if game_over %}
      <th colspan="2"></th>
      {% for p in players %}
      <th><p><span{% if game_over %} class="{{ p.team }}"{% endif %}>{{ p.role_string }}</span></p></th>
      {% endfor %}
    {% endif %}
  </thead>
  {% for game_round in game_rounds %}
  <tbody>
    {% for vote_round in game_round.voteround_set.all|dictsort:'vote_num' %}
    <tr class="{% if forloop.revcounter0 > 0 %}reject
      {% elif game_round.mission_passed != None %}{{ game_round.result_string }}
      {% elif vote_round.is_waiting_on_leader %}pending
      {% elif vote_round.is_currently_voting %}voting
      {% elif vote_round.is_voting_complete %}{% if game_over %}reject{% else %}accept-pending{% endif %}
      {% endif %}">
      {% if vote_round.is_voting_complete %}
      <td class="accept">{{ vote_round.vote_totals.accepts }}</td>
      <td class="reject">{{ vote_round.vote_totals.rejects }}</td>
      {% for pv in vote_round.playervote_set.all|dictsort:'player.order' %}
      <td class="{% if pv.player == vote_round.leader %}leader{% endif %} {% if pv.player in vote_round.chosen.all %}chosen {% if game_over and vote_round.team_approved %}{% if pv.player in game_round.played_fail %}played-fail{% else %}played-success{% endif %}{% endif %}{% endif %} {% if not private_voting or game_over %}{% if pv.accept %}accept{% else %}reject{% endif %}{% endif %}"></td>
      {% endfor %}
      {% else %}
      <td class="accept"></td>
      <td class="reject"></td>
      {% for p in players %}
      <td class="{% if p == vote_round.leader %}leader{% endif %} {% if vote_round.is_team_finalized and p in vote_round.chosen.all %}chosen{% endif %}"></td>
      {% endfor %}
      {% endif %}
    </tr>
    {% endfor %}
    {% if game_round.mission_passed != None %}
    <tr class="summary {{ game_round.result_string }}">
      <td colspan="{{ num_players|add:2 }}">
        Mission {{ game_round.round_num }} {{ game_round.result_string }}ed
        with {{ game_round.num_fails }} failures
      </td>
    </tr>
    {% elif game_over %}
    <tr class="summary fail">
      <td colspan="{{ num_players|add:2 }}">
        Mission {{ game_round.round_num }} failed as the resistance was unable
        to choose a team 5 times in a row
      </td>
    </tr>
    {% endif %}
  </tbody>
  {% endfor %}
  {% if player_assassinated %}
  <tbody>
    <tr class="assassin-round">
      {% for p in players %}
      <td{% if p == player_assassinated %} class="assassinated"{% endif %}></td>
      {% endfor %}
    </tr>
  </tbody>
  {% endif %}
</table>
{% endif %}
{% endblock %}

avalon/avalon_game/templates/join_game.html
{% extends "base.html" %}

{% block content %}
    <h2>Join Game</h2>

    <form class="join-game-form" action="{% url 'enter_code' %}" method="post">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>

      <div class="button-container">
        <input type="submit" class="button button-join" value="Join"></input>
        <input type="submit" class="button button-observe" name="observe" value="Observe"></input>
      </div>
      <div class="button-container">
        <a href="{% url 'index' %}" class="button button-main-menu">Back</a>
      </div>
    </form>
{% endblock %}